name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # كل يوم عند منتصف الليل
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate-gif
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
